// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: service/dex-finance/base.proto

package dex_finance

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CoinItem with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CoinItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CoinItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CoinItemMultiError, or nil
// if none found.
func (m *CoinItem) ValidateAll() error {
	return m.validate(true)
}

func (m *CoinItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Title

	// no validation rules for Img

	// no validation rules for Type

	// no validation rules for Round

	// no validation rules for BaseAmount

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CoinItemValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CoinItemValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CoinItemValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CoinItemValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CoinItemValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CoinItemValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CoinItemMultiError(errors)
	}

	return nil
}

// CoinItemMultiError is an error wrapping multiple validation errors returned
// by CoinItem.ValidateAll() if the designated constraints aren't met.
type CoinItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CoinItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CoinItemMultiError) AllErrors() []error { return m }

// CoinItemValidationError is the validation error returned by
// CoinItem.Validate if the designated constraints aren't met.
type CoinItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CoinItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CoinItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CoinItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CoinItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CoinItemValidationError) ErrorName() string { return "CoinItemValidationError" }

// Error satisfies the builtin error interface
func (e CoinItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCoinItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CoinItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CoinItemValidationError{}

// Validate checks the field values on AccountItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AccountItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AccountItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AccountItemMultiError, or
// nil if none found.
func (m *AccountItem) ValidateAll() error {
	return m.validate(true)
}

func (m *AccountItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for CoinId

	// no validation rules for Status

	// no validation rules for AccountType

	// no validation rules for Amount

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AccountItemValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AccountItemValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AccountItemValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AccountItemValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AccountItemValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AccountItemValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AccountItemMultiError(errors)
	}

	return nil
}

// AccountItemMultiError is an error wrapping multiple validation errors
// returned by AccountItem.ValidateAll() if the designated constraints aren't met.
type AccountItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AccountItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AccountItemMultiError) AllErrors() []error { return m }

// AccountItemValidationError is the validation error returned by
// AccountItem.Validate if the designated constraints aren't met.
type AccountItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccountItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccountItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccountItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccountItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccountItemValidationError) ErrorName() string { return "AccountItemValidationError" }

// Error satisfies the builtin error interface
func (e AccountItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccountItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccountItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccountItemValidationError{}
